class_name GameCatalog
extends RefCounted
## Catalogue de jeux connus : nom de processus (comme Activity.proc_name : minuscules, sans ".exe")
## -> {name, genre}. Plus quelques jeux de navigateur reconnus a leur titre de fenetre.
## Genres : strategy, card, puzzle, moba, fps, racing, sports, fighting, platformer, rpg, action,
##          sandbox, survival, sim, horror, party, rhythm.
## GameEvents s'en sert pour game_changed(proc, genre) ; strategy / card / puzzle -> lunettes + pose
## de reflexion.

const GAMES := {
	# ---------------------------------------------------------------- strategie
	"civilizationvi": ["Civilization VI", "strategy"],
	"civilizationvi_dx12": ["Civilization VI", "strategy"],
	"civilizationvii": ["Civilization VII", "strategy"],
	"civilizationv": ["Civilization V", "strategy"],
	"civilizationv_dx11": ["Civilization V", "strategy"],
	"aoe2de_s": ["Age of Empires II: DE", "strategy"],
	"aoe3de_s": ["Age of Empires III: DE", "strategy"],
	"reliccardinal": ["Age of Empires IV", "strategy"],
	"aomrt_s": ["Age of Mythology: Retold", "strategy"],
	"sc2_x64": ["StarCraft II", "strategy"],
	"sc2": ["StarCraft II", "strategy"],
	"starcraft": ["StarCraft", "strategy"],
	"warcraft iii": ["Warcraft III", "strategy"],
	"warhammer3": ["Total War: Warhammer III", "strategy"],
	"warhammer2": ["Total War: Warhammer II", "strategy"],
	"warhammer": ["Total War: Warhammer", "strategy"],
	"three_kingdoms": ["Total War: Three Kingdoms", "strategy"],
	"rome2": ["Total War: Rome II", "strategy"],
	"attila": ["Total War: Attila", "strategy"],
	"shogun2": ["Total War: Shogun 2", "strategy"],
	"medieval2": ["Medieval II: Total War", "strategy"],
	"stellaris": ["Stellaris", "strategy"],
	"hoi4": ["Hearts of Iron IV", "strategy"],
	"eu4": ["Europa Universalis IV", "strategy"],
	"eu5": ["Europa Universalis V", "strategy"],
	"ck3": ["Crusader Kings III", "strategy"],
	"ck2": ["Crusader Kings II", "strategy"],
	"victoria3": ["Victoria 3", "strategy"],
	"anno1800": ["Anno 1800", "strategy"],
	"anno117": ["Anno 117", "strategy"],
	"xcom2": ["XCOM 2", "strategy"],
	"xcomgame": ["XCOM: Enemy Unknown", "strategy"],
	"reliccoh3": ["Company of Heroes 3", "strategy"],
	"reliccoh2": ["Company of Heroes 2", "strategy"],
	"humankind": ["Humankind", "strategy"],
	"endlesslegend": ["Endless Legend", "strategy"],
	"oldworld": ["Old World", "strategy"],
	"northgard": ["Northgard", "strategy"],
	"theyarebillions": ["They Are Billions", "strategy"],
	"frostpunk": ["Frostpunk", "strategy"],
	"cities": ["Cities: Skylines", "strategy"],
	"cities2": ["Cities: Skylines II", "strategy"],
	"rimworldwin64": ["RimWorld", "strategy"],
	"factorio": ["Factorio", "strategy"],
	"oxygennotincluded": ["Oxygen Not Included", "strategy"],
	"breach": ["Into the Breach", "strategy"],
	"darkest": ["Darkest Dungeon", "strategy"],
	"darkest dungeon ii": ["Darkest Dungeon II", "strategy"],
	"fm": ["Football Manager", "strategy"],
	"manorlords-win64-shipping": ["Manor Lords", "strategy"],
	"manorlords": ["Manor Lords", "strategy"],
	"against the storm": ["Against the Storm", "strategy"],
	"forgedalliance": ["Supreme Commander: Forged Alliance", "strategy"],
	"songsofsyx": ["Songs of Syx", "strategy"],
	"banished": ["Banished", "strategy"],
	"tropico6": ["Tropico 6", "strategy"],
	"chess": ["Échecs", "strategy"],
	# ---------------------------------------------------------------- cartes
	"hearthstone": ["Hearthstone", "card"],
	"balatro": ["Balatro", "card"],
	"slaythespire": ["Slay the Spire", "card"],
	"lor": ["Legends of Runeterra", "card"],
	"snap": ["Marvel Snap", "card"],
	"mtga": ["Magic: The Gathering Arena", "card"],
	"gwent": ["Gwent", "card"],
	"inscryption": ["Inscryption", "card"],
	"masterduel": ["Yu-Gi-Oh! Master Duel", "card"],
	"solitaire": ["Microsoft Solitaire", "card"],
	"monster train": ["Monster Train", "card"],
	# ---------------------------------------------------------------- reflexion
	"portal2": ["Portal 2", "puzzle"],
	"witness64_d3d11": ["The Witness", "puzzle"],
	"baba is you": ["Baba Is You", "puzzle"],
	"mini metro": ["Mini Metro", "puzzle"],
	"islanders": ["Islanders", "puzzle"],
	"dorfromantik": ["Dorfromantik", "puzzle"],
	"tetris effect": ["Tetris Effect", "puzzle"],
	"talos2-win64-shipping": ["The Talos Principle 2", "puzzle"],
	"talos": ["The Talos Principle", "puzzle"],
	"outerwilds": ["Outer Wilds", "puzzle"],
	"lightning": ["Opus Magnum", "puzzle"],
	"the room": ["The Room", "puzzle"],
	# ---------------------------------------------------------------- MOBA
	"league of legends": ["League of Legends", "moba"],
	"dota2": ["Dota 2", "moba"],
	"deadlock": ["Deadlock", "moba"],
	"smite": ["Smite", "moba"],
	"heroesofthestorm_x64": ["Heroes of the Storm", "moba"],
	# ---------------------------------------------------------------- tir
	"cs2": ["Counter-Strike 2", "fps"],
	"csgo": ["Counter-Strike: GO", "fps"],
	"valorant-win64-shipping": ["Valorant", "fps"],
	"valorant": ["Valorant", "fps"],
	"overwatch": ["Overwatch 2", "fps"],
	"r5apex": ["Apex Legends", "fps"],
	"r5apex_dx12": ["Apex Legends", "fps"],
	"fortniteclient-win64-shipping": ["Fortnite", "fps"],
	"tslgame": ["PUBG: Battlegrounds", "fps"],
	"cod": ["Call of Duty", "fps"],
	"modernwarfare": ["Call of Duty: Modern Warfare", "fps"],
	"blackopscoldwar": ["Call of Duty: Black Ops Cold War", "fps"],
	"rainbowsix": ["Rainbow Six Siege", "fps"],
	"rainbowsix_be": ["Rainbow Six Siege", "fps"],
	"rainbowsix_vulkan": ["Rainbow Six Siege", "fps"],
	"bf2042": ["Battlefield 2042", "fps"],
	"bf6": ["Battlefield 6", "fps"],
	"bfv": ["Battlefield V", "fps"],
	"bf1": ["Battlefield 1", "fps"],
	"bf4": ["Battlefield 4", "fps"],
	"escapefromtarkov": ["Escape from Tarkov", "fps"],
	"destiny2": ["Destiny 2", "fps"],
	"tf_win64": ["Team Fortress 2", "fps"],
	"haloinfinite": ["Halo Infinite", "fps"],
	"mcc-win64-shipping": ["Halo: MCC", "fps"],
	"doometernalx64vk": ["DOOM Eternal", "fps"],
	"doomthedarkages": ["DOOM: The Dark Ages", "fps"],
	"marvel-win64-shipping": ["Marvel Rivals", "fps"],
	"marvelrivals": ["Marvel Rivals", "fps"],
	"discovery": ["The Finals", "fps"],
	"huntgame": ["Hunt: Showdown", "fps"],
	"left4dead2": ["Left 4 Dead 2", "fps"],
	"payday2_win32_release": ["Payday 2", "fps"],
	"helldivers2": ["Helldivers 2", "fps"],
	"borderlands3": ["Borderlands 3", "fps"],
	"borderlands4": ["Borderlands 4", "fps"],
	"warframe.x64": ["Warframe", "fps"],
	"titanfall2": ["Titanfall 2", "fps"],
	"readyornot-win64-shipping": ["Ready or Not", "fps"],
	"insurgencyclient-win64-shipping": ["Insurgency: Sandstorm", "fps"],
	"squadgame": ["Squad", "fps"],
	"arma3_x64": ["Arma 3", "fps"],
	"hl": ["Half-Life / Counter-Strike 1.6", "fps"],
	"hl2": ["Half-Life 2", "fps"],
	"hlvr": ["Half-Life: Alyx", "fps"],
	# ---------------------------------------------------------------- course
	"forzahorizon5": ["Forza Horizon 5", "racing"],
	"forzahorizon4": ["Forza Horizon 4", "racing"],
	"ac2-win64-shipping": ["Assetto Corsa Competizione", "racing"],
	"acs": ["Assetto Corsa", "racing"],
	"f1_24": ["F1 24", "racing"],
	"f1_25": ["F1 25", "racing"],
	"f1_23": ["F1 23", "racing"],
	"trackmania": ["Trackmania", "racing"],
	"beamng.drive.x64": ["BeamNG.drive", "racing"],
	"nfsunbound": ["Need for Speed Unbound", "racing"],
	"nfs heat": ["Need for Speed Heat", "racing"],
	"thecrewmotorfest": ["The Crew Motorfest", "racing"],
	"dirtrally2": ["DiRT Rally 2.0", "racing"],
	"iracingsim64dx11": ["iRacing", "racing"],
	# ---------------------------------------------------------------- sport
	"rocketleague": ["Rocket League", "sports"],
	"fc24": ["EA Sports FC 24", "sports"],
	"fc25": ["EA Sports FC 25", "sports"],
	"fc26": ["EA Sports FC 26", "sports"],
	"efootball": ["eFootball", "sports"],
	"nba2k25": ["NBA 2K25", "sports"],
	"nba2k26": ["NBA 2K26", "sports"],
	"golf with your friends": ["Golf With Your Friends", "sports"],
	# ---------------------------------------------------------------- combat
	"streetfighter6": ["Street Fighter 6", "fighting"],
	"polaris-win64-shipping": ["Tekken 8", "fighting"],
	"mk12": ["Mortal Kombat 1", "fighting"],
	"brawlhalla": ["Brawlhalla", "fighting"],
	"ggst-win64-shipping": ["Guilty Gear -Strive-", "fighting"],
	"dbfighterz": ["Dragon Ball FighterZ", "fighting"],
	# ---------------------------------------------------------------- plateformes
	"hollow_knight": ["Hollow Knight", "platformer"],
	"hollow knight silksong": ["Hollow Knight: Silksong", "platformer"],
	"celeste": ["Celeste", "platformer"],
	"cuphead": ["Cuphead", "platformer"],
	"supermeatboy": ["Super Meat Boy", "platformer"],
	"rayman legends": ["Rayman Legends", "platformer"],
	"spel2": ["Spelunky 2", "platformer"],
	"deadcells": ["Dead Cells", "platformer"],
	# ---------------------------------------------------------------- RPG / MMO
	"eldenring": ["Elden Ring", "rpg"],
	"nightreign": ["Elden Ring Nightreign", "rpg"],
	"witcher3": ["The Witcher 3", "rpg"],
	"cyberpunk2077": ["Cyberpunk 2077", "rpg"],
	"starfield": ["Starfield", "rpg"],
	"skyrimse": ["Skyrim Special Edition", "rpg"],
	"fallout4": ["Fallout 4", "rpg"],
	"bg3": ["Baldur's Gate 3", "rpg"],
	"bg3_dx11": ["Baldur's Gate 3", "rpg"],
	"eocapp": ["Divinity: Original Sin 2", "rpg"],
	"diablo iv": ["Diablo IV", "rpg"],
	"pathofexile": ["Path of Exile", "rpg"],
	"pathofexile_x64": ["Path of Exile", "rpg"],
	"pathofexilesteam": ["Path of Exile", "rpg"],
	"pathofexile_x64steam": ["Path of Exile", "rpg"],
	"genshinimpact": ["Genshin Impact", "rpg"],
	"starrail": ["Honkai: Star Rail", "rpg"],
	"zenlesszonezero": ["Zenless Zone Zero", "rpg"],
	"wow": ["World of Warcraft", "rpg"],
	"ffxiv_dx11": ["Final Fantasy XIV", "rpg"],
	"lostark": ["Lost Ark", "rpg"],
	"blackdesert64": ["Black Desert", "rpg"],
	"gw2-64": ["Guild Wars 2", "rpg"],
	"eso64": ["The Elder Scrolls Online", "rpg"],
	"monsterhunterwilds": ["Monster Hunter Wilds", "rpg"],
	"monsterhunterworld": ["Monster Hunter: World", "rpg"],
	"darksoulsiii": ["Dark Souls III", "rpg"],
	"sekiro": ["Sekiro", "rpg"],
	"hogwartslegacy": ["Hogwarts Legacy", "rpg"],
	"p5r": ["Persona 5 Royal", "rpg"],
	"metaphor": ["Metaphor: ReFantazio", "rpg"],
	"kingdomcome": ["Kingdom Come: Deliverance II", "rpg"],
	"dd2": ["Dragon's Dogma 2", "rpg"],
	"ffxvi": ["Final Fantasy XVI", "rpg"],
	# ---------------------------------------------------------------- action / aventure
	"gta5": ["GTA V", "action"],
	"gta5_enhanced": ["GTA V", "action"],
	"rdr2": ["Red Dead Redemption 2", "action"],
	"gow": ["God of War", "action"],
	"gowr": ["God of War Ragnarök", "action"],
	"re4": ["Resident Evil 4", "action"],
	"spider-man": ["Marvel's Spider-Man", "action"],
	"ghostoftsushima": ["Ghost of Tsushima", "action"],
	"sotgame": ["Sea of Thieves", "action"],
	"hades": ["Hades", "action"],
	"hades2": ["Hades II", "action"],
	"b1-win64-shipping": ["Black Myth: Wukong", "action"],
	"it takes two": ["It Takes Two", "action"],
	# ---------------------------------------------------------------- bac a sable / survie
	"minecraft.windows": ["Minecraft", "sandbox"],
	"minecraft": ["Minecraft", "sandbox"],
	"terraria": ["Terraria", "sandbox"],
	"robloxplayerbeta": ["Roblox", "sandbox"],
	"gmod": ["Garry's Mod", "sandbox"],
	"factorygamesteam-win64-shipping": ["Satisfactory", "sandbox"],
	"factorygame-win64-shipping": ["Satisfactory", "sandbox"],
	"factorygameegs-win64-shipping": ["Satisfactory", "sandbox"],
	"valheim": ["Valheim", "survival"],
	"rustclient": ["Rust", "survival"],
	"arkascended": ["ARK: Survival Ascended", "survival"],
	"palworld-win64-shipping": ["Palworld", "survival"],
	"subnautica": ["Subnautica", "survival"],
	"7daystodie": ["7 Days to Die", "survival"],
	"dontstarve_steam_x64": ["Don't Starve Together", "survival"],
	"sonsoftheforest": ["Sons of the Forest", "survival"],
	"theforest": ["The Forest", "survival"],
	"enshrouded": ["Enshrouded", "survival"],
	"deadbydaylight-win64-shipping": ["Dead by Daylight", "horror"],
	"phasmophobia": ["Phasmophobia", "horror"],
	"lethal company": ["Lethal Company", "horror"],
	"re2": ["Resident Evil 2", "horror"],
	# ---------------------------------------------------------------- simulation / detente
	"stardew valley": ["Stardew Valley", "sim"],
	"ts4_x64": ["Les Sims 4", "sim"],
	"planetcoaster": ["Planet Coaster", "sim"],
	"planetzoo": ["Planet Zoo", "sim"],
	"tph": ["Two Point Hospital", "sim"],
	"flightsimulator": ["Microsoft Flight Simulator", "sim"],
	"flightsimulator2024": ["Microsoft Flight Simulator 2024", "sim"],
	"eurotrucks2": ["Euro Truck Simulator 2", "sim"],
	"amtrucks": ["American Truck Simulator", "sim"],
	"farmingsimulator2025": ["Farming Simulator 25", "sim"],
	"farmingsimulator2022": ["Farming Simulator 22", "sim"],
	"powerwashsimulator": ["PowerWash Simulator", "sim"],
	# ---------------------------------------------------------------- jeux entre amis / rythme
	"among us": ["Among Us", "party"],
	"fallguys_client_game": ["Fall Guys", "party"],
	"osu!": ["osu!", "rhythm"],
	"beat saber": ["Beat Saber", "rhythm"],
}

## Jeux reconnus au titre de la fenetre (navigateur ou lanceur generique), en minuscules.
const TITLES := [
	["chess.com", "Chess.com", "strategy"], ["lichess", "Lichess", "strategy"],
	["échecs", "Échecs", "strategy"], ["sudoku", "Sudoku", "puzzle"], ["wordle", "Wordle", "puzzle"],
	["mots croisés", "Mots croisés", "puzzle"], ["mots fléchés", "Mots fléchés", "puzzle"],
	["crossword", "Mots croisés", "puzzle"], ["sutom", "Sutom", "puzzle"], ["geoguessr", "GeoGuessr", "puzzle"],
	["2048", "2048", "puzzle"], ["jigsaw", "Puzzle", "puzzle"], ["tetr.io", "Tetris", "puzzle"],
	["solitaire", "Solitaire", "card"], ["poker", "Poker", "card"], ["minecraft", "Minecraft", "sandbox"],
]
## Processus generiques ou seul le titre permet de conclure (Java, navigateurs).
const TITLE_HOSTS := ["javaw", "java", "chrome", "msedge", "firefox", "opera", "opera_gx", "brave", "vivaldi",
	"arc", "zen", "floorp", "applicationframehost"]


## {id, name, genre} si le jeu est connu, {} sinon. `proc` : nom de processus (sans .exe, casse libre).
static func lookup(proc: String, title: String) -> Dictionary:
	var p := proc.strip_edges().to_lower()
	if p.ends_with(".exe"):
		p = p.substr(0, p.length() - 4)
	if TITLE_HOSTS.has(p) or p == "":
		var t := title.to_lower()
		for e in TITLES:
			if t.contains(e[0]):
				return {"id": e[0], "name": e[1], "genre": e[2]}
		return {}
	if GAMES.has(p):
		var g: Array = GAMES[p]
		return {"id": p, "name": g[0], "genre": g[1]}
	return {}


## Genres « calmes, on reflechit » (lunettes + pose pensive).
static func is_thinking_genre(genre: String) -> bool:
	return genre in ["strategy", "card", "puzzle"]
